repos:
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-stan
        pass_filenames: false
        args:
          - "--memory-limit=2G"
      - id: php-lint
  - repo: https://github.com/larasense/pre-commit-php-laravel
    rev: 1.0.1
    hooks:
      - id: pest-test
